name: ex2

#this only occurs on the specified trigger below
on:
    #this is the trigger
    push:
        #specifies which branches this is executed on
        branches: ["master"]

    # useOutput: 
    #     runs-on: self-hosted
    #     needs: [createOutput]
        
    #     strategy:
    #         matrix:
    #             vars: [1,2,3,4,5,6,7,8,9,10]

    #     steps:
    #     - uses: actions/download-artifact@v3
    #       with:
    #         name: my-artifact
    #         # path: foo.txt

    #     - run: | 
    #         value=`cat foo.txt`
    #         echo $value - ${{matrix.vars}}
    #     - run: ex2.sh
    #       shell: bash 


jobs:
    passIn:
        runs-on: self-hosted
        name: passing in our string input
        steps:
            - uses: actions/checkout@v2
            - name: giving the action the string
              id: foo
              uses: ./.github/workflows/actions/myAction
              with:
                mString: "im being passed"
            - run: |
                echo "random-string=${{steps.foo.outputs.random-string}}" >> $GITHUB_OUTPUT

    display:
        runs-on: self-hosted
        needs: [passIn]

        strategy:
            matrix:
                vars: [1,2,3,4,5,6,7,8,9,10]
        steps:
            - run: |
                echo ${{needs.passIn.outputs}}-${{matrix.vars}}

            


