name: CI

#this only occurs on the specified trigger below
on:
    #this is the trigger
    push:
        #specifies which branches this is executed on
        branches: ["master"]


jobs: # this is where you define what you want to happen
    simple: # job name
        runs-on: ubuntu-latest # specify ehat os it should run on


        steps: # defining steps
            - name: run a one-line script
              env: 
                secret: ${{ secrets.SECRET_PASS}}
              run: echo secret
