name: CI

#this only occurs on the specified trigger below
on:
    #this is the trigger
    push:
        #specifies which branches this is executed on
        branches: ["master"]


jobs: # this is where you define what you want to happen
    simple: # job name
        runs-on: ubuntu-latest # specify ehat os it should run on

        steps: # defining steps
            - name: run a one-line script
              run: echo ${{ secrets.SECRET_PASS }}

    string_out:
        runs-on: ubuntu-latest

        steps:
            - name: create string
              run: |
                myout = "hello world"
              id: myout
            - name: 
              run: |
                echo "my strin is: ${{steps.myout.outputs.content}}"


    
